version: '1.2'
services:
  frontend-api:
    container_name: kupipodariday-frontend
    build: ./frontend
    restart: always
    volumes:
      - "./frontend/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    ports: 
      - 8081:80
  backend-api:
    container_name: kupipodariday-backend
    build: ./backend
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - postgres
  postgres:
    container_name: kupipodariday-database
    image: postgres:12
    env_file: ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  postgres-data:
    driver: local