version: '1.0'
services:
  backend-api:
    container_name: kupipodariday-backend
    build: .
    restart: always
    ports:
      - 4000:3000
    depends_on:
      - postgres
  postgres:
    image: "postgres:12"
    env_file: .env  
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata 
volumes:
  postgres-data:
    driver: local
